### ISSUE TITLE
Uncaught TIMEOUT

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#10601]
## Issue - Bug

- **How serious is the bug?** P3?
- **OS:** macOS / Linux / Windows / ?
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Node version:** `node --version`
- **NPM version:** `npm --version`
- Parabol v8.12.3

```
{"time":"2024-12-13T09:43:24.389Z","level":"info","message":"\n🔥🔥🔥 Server ID: 221. Ready for Sockets: Port 3000 🔥🔥🔥 []"}                                                                                     
(node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.                         
(Use `node --trace-deprecation ...` to show where the warning was created)                                                                                                                                         
{"time":"2024-12-13T09:43:34.964Z","level":"info","message":"SEND TO SENTRY [\n  Error: GQL executor took too long to respond\n      at publishInternalGQL (/home/node/parabol/dist/web.js:188754:43)\n      at run
NextTicks (node:internal/process/task_queues:60:5)\n      at listOnTimeout (node:internal/timers:545:9)\n      at process.processTimers (node:internal/timers:519:7)\n      at async Promise.all (index 0)\n      a
t async ScanStream.<anonymous> (/home/node/parabol/dist/web.js:189239:7)\n]"}                                                                                                                                      
{"time":"2024-12-13T09:43:34.983Z","level":"info","message":"SEND TO SENTRY [\n  Error: GQL executor took too long to respond\n      at publishInternalGQL (/home/node/parabol/dist/web.js:188754:43)\n      at asy
nc Promise.all (index 1)\n      at async ScanStream.<anonymous> (/home/node/parabol/dist/web.js:189239:7)\n]"}                                                                                                     
{"time":"2024-12-13T10:00:12.552Z","level":"info","message":"SEND TO SENTRY [\n  Error: GQL executor took too long to respond\n      at publishInternalGQL (/home/node/parabol/dist/web.js:188754:43)\n      at asy
nc handleDisconnect (/home/node/parabol/dist/web.js:182151:5)\n]"}
                                                                                                                                                 
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:                   
Error: TIMEOUT                                                                                                                                                                                                     
    at Timeout._onTimeout (/home/node/parabol/dist/web.js:185218:16)                                                                                                                                               
    at listOnTimeout (node:internal/timers:581:17)                                                                                                                                                                 
    at process.processTimers (node:internal/timers:519:7)                                                                                                                                                          
```

### Acceptance Criteria (optional)

Users can:

- Do this
- Do that
- Cannot do that
  Triage is performed to find the root cause of the bug, timeboxed to ~1 hour.

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by dbumblis-parabol** [comment]
It looks like the executor default deployment [strategy](https://gitlab.com/parabol1/saas/parabol/-/blob/main/production/values.yaml?ref_type=heads) is the following:
```
strategy:
      # -- Recreate would provoke a downtime on the application
      type: "RollingUpdate"
      # -- It is preferred to deploy all new pods and replace the old ones at once, but some unavailable pods are allowed
      rollingUpdate:
        maxSurge: "100%"
        maxUnavailable: "25%"
```
New pods should've started prior to any executors being terminated and that is the behavior that is usually seen on a helm chart upgrade.

**Comment by mattkrick** [comment]
that code looks good!
...but the link included shows the following:

```
graphqlExecutor:
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: saas-production-gqlex@parabol-saas-production.iam.gserviceaccount.com
  deployment:
    replicaCount: 3
    resources:
      limits:
        memory: 4096Mi
      requests:
        cpu: 1000m
        memory: 4096Mi
  ephemeralStorage:
    enabled: false
    storage: 1Gi
```

where did that codeblock come from?
