### ISSUE TITLE
Re-connection to databases: retry and DNS refresh

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#7570]
## Issue - Enhancement+Bug

We have observed that the application is not able to reconnect to the databases (Redis, RethinkDB and PostgreSQL) if the IP of the database changes.

The DNS isn't resolved again, which is a problem in ephemeral and dynamic environments such as in the Cloud or in any Kubernetes cluster.

The retry mechanism should be an exponential backoff, to reduce the charge on the databases, in case there is a problem and the database is unresponsive.

### Acceptance Criteria

- [ ] The application retries the connection to **Redis** and resolves again the DNS if the cached endpoint does not respond.
- [ ] The application retries the connection to **PostgreSQL** and resolves again the DNS if the cached endpoint does not respond.
- [ ] The application retries the connection to **RethinkDB** and resolves again the DNS if the cached endpoint does not respond.

**Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I believe this is prioritized correctly. Thank you for opening this one

**Comment by jordanh** [comment]
The old networking dork in my is curious and I'd like to document here what we know already...

- Does the host system resolve the new address correctly or is node caching the wrong address?
- What are the DNS TTL values of our database servers?
- How do other folks solve this in node today?

**Comment by rafaelromcar-parabol** [comment]
Sorry @jordanh I didn't answer to your questions

> * Does the host system resolve the new address correctly or is node caching the wrong address?
- Kubernetes services resolve to the IP of the new pod once it is up and available. It must be our application (probably the rethinkdb client?) not retrying once the connection is cut.

> * What are the DNS TTL values of our database servers?
- In GCP Cloud DNS we are setting up for Redis and PostgreSQL a 300s TTL. 
- In Kubernetes, the default internal dns server that resolves the local services has a 30s TTL by default.

> * How do other folks solve this in node today?
- Question for @mattkrick and @Dschoordsch I think

**Comment by mattkrick** [comment]
Stuck on reproduction steps.

I tried the following & it healed itself without requiring a server restart 
 
```sh
docker stop <RETHINK_ID>
docker start <RETHINK_ID>
```

**Comment by rafaelromcar-parabol** [comment]
Sorry for the late reply here @mattkrick. I've been testing on my side and I cannot reproduce the problem, which I don't understand...

That said, if you want to emulate a IP change using Docker Compose you need to modify the file [dev.yaml](https://github.com/ParabolInc/parabol/blob/master/docker/dev.yml), used in `yarn db:start` in two points:
- The network parabol-network has a defined subnet.
- The service (container) **db** has a defined ipv4_address using a shell environment variable **RDB_IP**.

Modified pieces of the file:
- Service db:
```
services:
  db:
    platform: linux/x86_64
    image: rethinkdb:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "29015:29015"
      - "28015:28015"
    volumes:
      - rethink-data:/data
    networks:
      # - parabol-network
      parabol-network:
        ipv4_address: ${RDB_IP}
  [THE REST OF SERVICES COME HERE]


networks:
  parabol-network:
    ipam:
      config:
        - subnet: ${DEV_SUBNET}
[THE VOLUMES ARE HERE]
```

Then, you have to define two environment variables:
- The subnet range: `export DEV_SUBNET=10.5.0.0/16`
- The IP for the RethinkDB container: `export RDB_IP=10.5.0.50`

Now, you can start the databases with `yarn db:start` and run the application with `yarn dev`. Check that everything works as expected.

To check the IP of all the running containers use:
```
docker ps --format "{{.Names}}" | while read cid b; do echo -n "$cid\t\t"; docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $cid; done
```
Or just the one for RethinkDB: `docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' docker-db-1`

To change that IP:
```
export RDB_IP=10.5.0.52

yarn db:start
```

You should see now, using the commands shared above, that the IP of that container has changed. If the application still works correctly, you haven't reproduced the problem.

So far, I haven't been able to reproduce it locally or in Kubernetes today. I'll think about how is this possible.
